name: Release New Version

env:
  NPM_TOKEN: ${{secrets.NPM_TOKEN}}

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Release type - major, minor or patch'
        required: false
        default: 'patch'

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Setup Node version
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Setup Git
        run: |
          git config --global user.name "devx-sauce-bot"
          git config --global user.email "devx.bot@saucelabs.com"

      - name: Install dependencies
        run: npm ci

      - name: Generate release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          npx release-it --dry-run ${{ github.event.inputs.releaseType }}
